export const ComponentIDs = {
  addCardHolderName: 'addCardHolderName',
  addCardHolderNumber: 'addCardHolderNumber',
  addCardExpiration: 'addCardExpiration',
  addCardCV: 'addCardCV',
  addPaymentFormSubmit: 'addPaymentFormSubmit',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  profilesMenuItem: 'profilesMenuItem',
  projectsMenuItem: 'projectsMenuItem',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormSubmit: 'signUpFormSubmit',
};

export const PageIDs = {
  addPayment: 'addPayment',
  filterPage: 'filterPage',
  homePage: 'homePage',
  interestsPage: 'interestsPage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  profilesPage: 'profilesPage',
  projectsPage: 'projectsPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
};
